@extends('theme.layouts.frontend')
@section('content')
<div class="checkout-page" id="checkout-page">
    <div class="page"><nav class="breadcrumb"><a href="{{ route('home') }}">হোম</a><i class="bi bi-chevron-right"></i><a href="{{ route('products') }}">পণ্য</a><i class="bi bi-chevron-right"></i><span class="active">{{ ($reviewLogin ?? false) ? 'রিভিউ দিতে লগইন' : 'চেকআউট' }}</span></nav>
    @unless($reviewLogin ?? false)<div class="page-head"><div><h1 class="page-title">চেকআউট</h1><p class="page-subtitle">পণ্য, ডেলিভারি ও Main Balance যাচাই করে অর্ডার নিশ্চিত করুন</p></div><div class="steps"><span class="step done"><i class="bi bi-check-lg"></i> ১. কার্ট</span><span class="step active">২. চেকআউট</span><span class="step">৩. নিশ্চিত</span></div></div>@endunless
    @if(!$quote)
        <section class="panel purchase-login"><div class="panel-body"><h2>{{ ($reviewLogin ?? false) ? 'রিভিউ দিতে লগইন করুন' : 'অর্ডার করতে লগইন করুন' }}</h2><p>{{ ($reviewLogin ?? false) ? 'লগইনের পর পণ্যের রিভিউ অংশে ফিরে যাবেন।' : 'আপনার কার্টের পণ্য লগইনের পর চেকআউটে আসবে।' }}</p><form method="post" action="{{ route('user.login') }}">@csrf<label for="purchase-identity">মোবাইল অথবা ইমেইল</label><input id="purchase-identity" name="identity" value="{{ old('identity') }}" required maxlength="191" autocomplete="username"><label for="purchase-password">পাসওয়ার্ড</label><input id="purchase-password" type="password" name="password" required autocomplete="current-password">@if($errors->any())<p class="purchase-error" role="alert">{{ $errors->first() }}</p>@endif<button type="submit" class="confirm-btn">{{ ($reviewLogin ?? false) ? 'লগইন করে রিভিউ দিন' : 'লগইন করে চেকআউটে যান' }}</button></form><a href="{{ route('products') }}">পণ্য দেখতে ফিরে যান</a></div></section>
    @else
    <div class="checkout-grid"><div class="left-stack">
        <section class="panel"><div class="panel-body"><div class="section-head"><h2 class="section-title"><i class="bi bi-geo-alt"></i> ডেলিভারি</h2><button id="editAddressButton" class="text-link" type="button">পরিবর্তন</button></div>
            <div class="address-box"><div class="address-icon"><i class="bi bi-geo-alt-fill"></i></div><div class="address-text"><strong id="addressPreviewName"></strong><span id="addressPreviewLine"></span></div><i class="bi bi-check-circle-fill" style="color:var(--green)"></i></div>
            <div id="addressManager" class="address-manager"><div id="savedAddressList" class="saved-address-list"></div><div class="address-manager-actions"><button id="addNewAddressButton" class="add-address-btn" type="button"><i class="bi bi-plus-lg"></i> নতুন ঠিকানা</button><button id="closeAddressManager" class="close-address-btn" type="button">বন্ধ করুন</button></div>
                <form id="addressForm" class="address-form" action="{{ route('checkout.address') }}" method="post">@csrf<input type="hidden" name="id" id="addressId"><div class="address-form-title"><span id="addressFormTitle">নতুন ঠিকানা যোগ করুন</span><i class="bi bi-house-add"></i></div><div class="address-editor-grid">
                    <div class="address-field"><label for="addressLabel">লেবেল</label><select id="addressLabel" name="label"><option>বাসা</option><option>অফিস</option><option>অন্যান্য</option></select></div><div class="address-field"><label for="addressName">নাম</label><input id="addressName" name="name" required maxlength="150" autocomplete="name"></div><div class="address-field"><label for="addressMobile">মোবাইল</label><input id="addressMobile" name="mobile" type="tel" required maxlength="20" placeholder="01XXXXXXXXX" autocomplete="tel"></div>
                    <div class="address-field"><label for="addressDistrict">জেলা</label><input id="addressDistrict" name="district" required maxlength="150" placeholder="যেমন: Dhaka" autocomplete="address-level2" list="districtOptions"><datalist id="districtOptions"><option value="Dhaka"><option value="Chattogram"><option value="Rajshahi"><option value="Khulna"><option value="Sylhet"><option value="Barishal"><option value="Cumilla"><option value="Rangpur"><option value="Mymensingh"></datalist></div><div class="address-field full"><label for="addressFull">সম্পূর্ণ ঠিকানা</label><input id="addressFull" name="address" required maxlength="500" placeholder="বাড়ি, রোড, এলাকা, জেলা" autocomplete="street-address"></div><div class="address-field"><label for="addressArea">এলাকা</label><input id="addressArea" name="area" maxlength="150"></div><div class="address-field"><label for="addressPostal">পোস্ট কোড</label><input id="addressPostal" name="postal_code" maxlength="20" autocomplete="postal-code"></div><label class="default-check"><input id="addressDefault" name="is_default" type="checkbox" value="1">এই ঠিকানাটি Default হিসেবে রাখুন</label><div class="address-editor-actions"><button id="cancelAddressEdit" class="address-cancel" type="button">বাতিল</button><button id="saveAddressEdit" class="address-save" type="submit"><i class="bi bi-check2"></i> সেভ করুন</button></div>
                </div></form>
            </div><div class="delivery-row" id="deliveryOptions"></div>
        </div></section>
        <section class="panel"><div class="panel-body"><div class="section-head"><h2 class="section-title"><i class="bi bi-ticket-perforated"></i> কুপন</h2></div><form class="coupon-row" id="couponForm"><input id="couponInput" type="text" maxlength="100" placeholder="কুপন কোড লিখুন" autocomplete="off" aria-label="কুপন কোড"><button id="applyCoupon" type="submit">প্রয়োগ</button><button id="removeCoupon" type="button" aria-label="কুপন সরান" hidden>×</button></form></div></section>
        <section class="panel balance-card"><div class="balance-head"><i class="bi bi-wallet2"></i> MAIN BALANCE</div><div class="balance-body"><div class="balance-row"><span>বর্তমান ব্যালেন্স</span><strong id="currentBalance"></strong></div><div class="balance-row"><span>আজ Products-এর জন্য</span><strong id="productsToday"></strong></div><div class="balance-row"><span>Delivery</span><strong id="deliveryAmount"></strong></div><div class="balance-row"><span>Discount</span><strong id="discountAmount"></strong></div><div class="balance-row total"><span>আজ প্রয়োজন</span><strong id="todayRequired"></strong></div><div class="balance-row remaining"><span>অর্ডারের পর থাকবে</span><strong id="remainingBalance"></strong></div></div><div id="balanceStatus" class="balance-status"></div></section>
        <label class="order-note-label" for="customerNote">অর্ডার সম্পর্কে কোনো নির্দেশনা (ঐচ্ছিক)</label><textarea id="customerNote" maxlength="500" rows="2" placeholder="ডেলিভারি সম্পর্কিত নির্দেশনা"></textarea>
        <button id="desktopConfirm" class="confirm-btn desktop-confirm" type="button"><i class="bi bi-shield-check"></i> Main Balance থেকে অর্ডার নিশ্চিত করুন</button><button id="depositButton" class="deposit-btn" type="button"><i class="bi bi-wallet"></i> প্রয়োজনীয় টাকা Deposit করুন</button>
        <details class="panel deposit-panel" id="depositPanel"><summary>ডিপোজিট আবেদন ও অবস্থা</summary><div class="panel-body">@if($paymentMethods->isNotEmpty())<form id="depositForm" method="post" action="{{ route('checkout.deposit') }}" enctype="multipart/form-data">@csrf<label for="depositMethod">পেমেন্ট পদ্ধতি</label><select id="depositMethod" name="payment_method_id" required>@foreach($paymentMethods as $method)<option value="{{ $method->id }}">{{ $method->name }}</option>@endforeach</select><div id="depositInstructions" class="deposit-instructions"></div><label for="depositAmount">টাকার পরিমাণ</label><input id="depositAmount" name="amount" type="number" min="1" max="9999999" step="0.01" required><label for="depositMobile">যে নম্বর থেকে পাঠিয়েছেন</label><input id="depositMobile" name="payer_mobile" type="tel" maxlength="20" required><label for="depositTransaction">ট্রানজ্যাকশন আইডি</label><input id="depositTransaction" name="transaction_id" maxlength="191" required><label for="depositScreenshot">রসিদের ছবি (ঐচ্ছিক, সর্বোচ্চ ২ MB)</label><input id="depositScreenshot" name="screenshot" type="file" accept="image/jpeg,image/png,image/webp"><p>টাকা পাঠানোর পর আবেদন জমা দিন। যাচাই ও অনুমোদনের পর ব্যালেন্স যোগ হবে।</p><button class="confirm-btn" type="submit">ডিপোজিট আবেদন জমা দিন</button></form>@else<p>এখন কোনো ডিপোজিট পদ্ধতি চালু নেই।</p>@endif<div class="deposit-history">@foreach($deposits as $deposit)<p>{{ $deposit->paymentMethod?->name }} · ৳ {{ number_format((float) $deposit->amount, 2) }} · {{ [0 => 'যাচাই চলছে', 1 => 'অনুমোদিত', 2 => 'বাতিল'][$deposit->status] ?? 'অপেক্ষমাণ' }}</p>@endforeach</div><button type="button" id="refreshBalance" class="text-link">ব্যালেন্স আবার দেখুন</button></div></details>
    </div><section class="panel cart-panel"><div class="cart-head"><div class="cart-head-top"><h2>কার্ট সারাংশ</h2><span class="item-count" id="itemCount"></span></div><div class="quick-row"><span class="quick-label">দ্রুত নির্বাচন:</span><button id="allCash" class="quick-btn" type="button"><i class="bi bi-cash"></i> সব নগদে</button><button id="allInstallment" class="quick-btn installment" type="button"><i class="bi bi-calendar2-week"></i> যেখানে সম্ভব কিস্তিতে</button></div></div><div id="productList" class="products"></div><div id="emptyCart" class="empty-cart"><i class="bi bi-cart-x"></i><p>কার্টে কোনো পণ্য নেই</p><a href="{{ route('products') }}">পণ্য দেখুন</a></div></section></div>
    <div class="mobile-sticky"><div class="sticky-total"><span>আজ প্রয়োজন</span><strong id="mobileTotal"></strong></div><button id="mobileConfirm" type="button">অর্ডার নিশ্চিত করুন</button></div>
    @endif
    </div>
</div>
@endsection
@push('style')<link rel="stylesheet" href="{{ asset('assets/theme/css/checkout.css') }}">@endpush
@push('script')
@if($quote)
<script>window.purchaseCheckout = {{ Illuminate\Support\Js::from(['quote' => $quote, 'addresses' => $addresses, 'paymentMethods' => $paymentMethods, 'token' => $checkoutToken, 'csrf' => csrf_token(), 'urls' => ['quote' => route('checkout.quote'), 'cart' => route('checkout.cart'), 'address' => route('checkout.address'), 'order' => route('checkout.store')]]) }};</script>
<script src="{{ asset('assets/theme/js/checkout.js') }}" defer></script>
@endif
@endpush
