@extends('theme.layouts.frontend')
@section('content')
@php
    $statusLabels = ['pending_approval' => 'অনুমোদনের অপেক্ষায়', 'approved' => 'অনুমোদিত', 'processing' => 'প্রসেসিং', 'completed' => 'সম্পন্ন', 'rejected' => 'বাতিল করা হয়েছে', 'cancelled' => 'বাতিল', 'returned' => 'ফেরত', 'payment_pending' => 'পেমেন্টের অপেক্ষায়'];
    $paymentLabels = ['paid' => 'সম্পূর্ণ পরিশোধিত', 'initial_paid' => 'প্রাথমিক পেমেন্ট সম্পন্ন', 'unpaid' => 'অপরিশোধিত', 'refunded' => 'ফেরত দেওয়া হয়েছে', 'refund_pending' => 'ফেরতের অপেক্ষায়'];
    $money = fn ($value) => '৳ '.number_format((float) $value, 2);
@endphp
<div class="confirmation-page" id="confirmation-page"><div class="page"><nav class="breadcrumb"><a href="{{ route('home') }}">হোম</a> › <a href="{{ route('checkout') }}">চেকআউট</a> › নিশ্চিত</nav><div class="steps"><div class="step done"><i class="bi bi-check-lg"></i> ১. কার্ট</div><div class="line"></div><div class="step done"><i class="bi bi-check-lg"></i> ২. চেকআউট</div><div class="line"></div><div class="step active">৩. নিশ্চিত</div></div>
    <section class="success-card"><div class="success-icon"><i class="bi bi-check-lg"></i></div><h1>অর্ডার সফলভাবে গ্রহণ করা হয়েছে</h1><p class="sub">আপনার অর্ডার ও পেমেন্টের তথ্য সংরক্ষিত আছে। সর্বশেষ অবস্থা নিচে দেখুন।</p><div class="order-meta"><div class="meta-box"><span>Order Number</span><strong>#{{ $order->order_no }}</strong></div><div class="meta-box"><span>মোট পণ্য</span><strong>{{ $order->items->sum('quantity') }}টি</strong></div></div>
        <div class="money-grid"><div class="money-box debit"><span>Main Balance থেকে কাটা হয়েছে</span><strong>{{ $money($order->balance_used) }}</strong></div><div class="money-box balance"><span>বর্তমান Main Balance</span><strong>{{ $money(auth()->user()->balance) }}</strong></div></div>
        @if($order->remaining_amount > 0)<div class="notice"><i class="bi bi-calendar2-week"></i><div><strong>পরবর্তী কিস্তিতে পরিশোধযোগ্য {{ $money($order->remaining_amount) }}</strong>প্রতিটি কিস্তির তারিখ ও পরিমাণ অর্ডারের বিস্তারিত অংশে দেখুন।</div></div>@endif
        <div class="summary"><div class="summary-row"><span>Order Status</span><strong class="{{ $order->order_status === 'pending_approval' ? 'pending' : '' }}">{{ $statusLabels[$order->order_status] ?? $order->order_status }}</strong></div><div class="summary-row"><span>Payment</span><strong class="paid">Main Balance · {{ $paymentLabels[$order->payment_status] ?? $order->payment_status }}</strong></div><div class="summary-row"><span>Delivery</span><strong>{{ $order->shippingMethod?->name ?? 'ডেলিভারি' }} — {{ $money($order->shipping_charge) }}</strong></div><div class="summary-row"><span>অর্ডারের তারিখ</span><strong>{{ $order->created_at->format('d M Y, h:i A') }}</strong></div></div>
        <div class="actions"><button type="button" class="btn primary" data-open="orderDetails"><i class="bi bi-receipt"></i> অর্ডারের বিস্তারিত দেখুন</button><button type="button" class="btn" data-open="orderHistory"><i class="bi bi-bag"></i> আমার অর্ডারসমূহ</button><a href="{{ route('products') }}" class="btn green"><i class="bi bi-cart-plus"></i> কেনাকাটা চালিয়ে যান</a></div>
    </section>
    <details class="receipt-panel" id="orderDetails"><summary>অর্ডারের বিস্তারিত · #{{ $order->order_no }}</summary><div class="receipt-body"><div class="receipt-head"><div><h2>অর্ডার রসিদ</h2><p>{{ $order->order_no }}</p></div><button type="button" id="printReceipt" class="btn">প্রিন্ট করুন</button></div><div class="receipt-address"><strong>{{ $order->shipping_name }}</strong><p>{{ $order->shipping_mobile }}<br>{{ $order->shipping_address }}<br>{{ $order->shipping_district }}</p></div><div class="receipt-table-wrap"><table class="receipt-table"><thead><tr><th>পণ্য</th><th>পরিমাণ</th><th>ধরন</th><th>মোট</th><th>প্রাথমিক পেমেন্ট</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product_name }}<small>{{ $item->sku }}</small>@if($item->installment_plan_name)<small>{{ $item->installment_plan_name }}</small>@endif</td><td>{{ $item->quantity }}</td><td>{{ $item->purchase_mode === 'cash' ? 'নগদ' : 'কিস্তি' }}</td><td>{{ $money($item->total_price) }}</td><td>{{ $money($item->initial_payable) }}</td></tr>@endforeach</tbody></table></div><div class="summary"><div class="summary-row"><span>পণ্যের মোট মূল্য</span><strong>{{ $money($order->subtotal) }}</strong></div><div class="summary-row"><span>কুপন ছাড়</span><strong>−{{ $money($order->discount_amount) }}</strong></div><div class="summary-row"><span>ডেলিভারি চার্জ</span><strong>{{ $money($order->shipping_charge) }}</strong></div><div class="summary-row"><span>সর্বমোট</span><strong>{{ $money($order->grand_total) }}</strong></div><div class="summary-row"><span>এখন পর্যন্ত পরিশোধ</span><strong>{{ $money($order->paid_amount) }}</strong></div><div class="summary-row"><span>বাকি</span><strong>{{ $money($order->remaining_amount) }}</strong></div>@if($transaction)<div class="summary-row"><span>পেমেন্ট ট্রানজ্যাকশন</span><strong>{{ $transaction->trx }}</strong></div><div class="summary-row"><span>অর্ডারের পর ব্যালেন্স</span><strong>{{ $money($transaction->post_balance) }}</strong></div>@endif</div>
        @if($order->customer_note)<p class="receipt-note">আপনার নির্দেশনা: {{ $order->customer_note }}</p>@endif
        @if($order->installments->isNotEmpty())<h3>কিস্তির সময়সূচি</h3><div class="receipt-table-wrap"><table class="receipt-table"><thead><tr><th>পণ্য / কিস্তি</th><th>তারিখ</th><th>টাকা</th><th>অবস্থা</th></tr></thead><tbody>@foreach($order->installments as $installment)<tr><td>{{ $order->items->firstWhere('id', $installment->order_item_id)?->product_name }}<small>কিস্তি #{{ $installment->installment_no }}</small></td><td>{{ $installment->due_date->format('d M Y') }}</td><td>{{ $money($installment->amount) }}</td><td>{{ ['pending' => 'অপেক্ষমাণ', 'paid' => 'পরিশোধিত', 'overdue' => 'সময় পার হয়েছে', 'cancelled' => 'বাতিল'][$installment->status] ?? $installment->status }}</td></tr>@endforeach</tbody></table></div>@endif
    </div></details>
    <details class="receipt-panel" id="orderHistory" @if(request('page')) open @endif><summary>আমার অর্ডারসমূহ</summary><div class="receipt-body">@foreach($otherOrders as $previous)<a class="order-history-row" href="{{ route('order.confirmation', $previous->order_no) }}"><span><strong>#{{ $previous->order_no }}</strong><small>{{ $previous->created_at->format('d M Y') }} · {{ $statusLabels[$previous->order_status] ?? $previous->order_status }}</small></span><strong>{{ $money($previous->grand_total) }}</strong></a>@endforeach<div class="history-pagination">@if($otherOrders->previousPageUrl())<a href="{{ $otherOrders->previousPageUrl() }}#orderHistory">আগের পৃষ্ঠা</a>@endif @if($otherOrders->nextPageUrl())<a href="{{ $otherOrders->nextPageUrl() }}#orderHistory">পরের পৃষ্ঠা</a>@endif</div></div></details>
</div></div>
@endsection
@push('style')<link rel="stylesheet" href="{{ asset('assets/theme/css/order-confirmation.css') }}">@endpush
@push('script')<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('#confirmation-page [data-open]').forEach(button=>button.addEventListener('click',()=>{const target=document.getElementById(button.dataset.open);target.open=true;target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}));document.getElementById('printReceipt').addEventListener('click',()=>window.print());});</script>@endpush
