@extends('theme.layouts.frontend')
@section('content')
@php($money = fn ($value) => \App\Services\PurchaseService::money($value))
<div class="product-detail-page" id="product-page">
    <div class="breadcrumb-area"><nav class="breadcrumb-custom"><a href="{{ route('home') }}">হোম</a><i class="fa-solid fa-chevron-right"></i><a href="{{ route('products', ['category' => $product->category?->slug]) }}">{{ $product->category?->name ?? 'পণ্য' }}</a><i class="fa-solid fa-chevron-right"></i><span>{{ $product->name }}</span></nav></div>
    <section class="product-layout">
        <div class="gallery-card"><div class="main-image">@if($images)<img id="mainProductImage" src="{{ $images[0] }}" alt="{{ $product->name }}"><button type="button" class="zoom-btn" id="imageZoom" aria-label="ছবি বড় করে দেখুন"><i class="fa-solid fa-expand"></i></button>@else<div class="purchase-image-placeholder"><i class="fa-solid fa-box-open"></i><span>ছবি এখনও যোগ করা হয়নি</span></div>@endif</div>
            @if(count($images) > 1)<button type="button" class="view-360" id="galleryOpen"><i class="fa-solid fa-images"></i> সব ছবি দেখুন</button><div class="thumbnail-list">@foreach($images as $image)<button type="button" class="thumb {{ $loop->first ? 'active' : '' }}" data-image-index="{{ $loop->index }}" aria-label="ছবি {{ $loop->iteration }}"><img src="{{ $image }}" alt="{{ $product->name }} — {{ $loop->iteration }}" loading="lazy"></button>@endforeach</div>@endif
        </div>
        <div class="product-info-panel"><h1 class="product-title">{{ $product->name }}</h1><div class="meta-line"><span>ব্র্যান্ড: <a href="{{ route('products', ['brand' => [$product->brand?->slug]]) }}">{{ $product->brand?->name ?? 'প্রযোজ্য নয়' }}</a></span><span>ক্যাটাগরি: {{ $product->category?->name }}</span></div><div class="sku">SKU: <span id="productSku">{{ $selected['sku'] }}</span></div>
            <div class="rating-row"><div class="rating-stars" aria-label="রেটিং {{ round($rating, 1) }}">@for($star = 1; $star <= 5; $star++)<i class="{{ $star <= round($rating) ? 'fa-solid' : 'fa-regular' }} fa-star"></i>@endfor</div><span class="rating-number">{{ number_format($rating, 1) }}</span><a href="#reviews" class="review-count" data-tab-link="reviews">({{ $reviewCount }}টি রিভিউ)</a><span class="stock-label" id="productStock">{{ $selected['stock'] > 0 ? '● স্টকে আছে' : 'স্টক নেই' }}</span></div>
            <div class="mini-benefits"><div class="mini-benefit"><div class="mini-benefit-icon"><i class="fa-solid fa-wallet"></i></div><div><strong>Main Balance</strong><span>অ্যাকাউন্ট থেকে পেমেন্ট</span></div></div><div class="mini-benefit"><div class="mini-benefit-icon"><i class="fa-solid fa-truck"></i></div><div><strong>ডেলিভারি সুবিধা</strong><span>এলাকা অনুযায়ী চার্জ</span></div></div><div class="mini-benefit"><div class="mini-benefit-icon"><i class="fa-solid fa-calendar-days"></i></div><div><strong>{{ $product->installment_enabled ? 'কিস্তিতে কেনাকাটা' : 'এককালীন মূল্য' }}</strong><span>পছন্দের পেমেন্ট পদ্ধতি</span></div></div></div>
            @if($product->has_variant)<div class="option-section"><div class="option-title">ভ্যারিয়েন্ট নির্বাচন করুন</div><div class="option-row" id="variantOptions">@foreach($variants as $variant)<button type="button" class="option-btn {{ $variant['variant_id'] === ($variants[0]['variant_id'] ?? null) ? 'active' : '' }}" data-variant="{{ $variant['variant_id'] }}" @disabled($variant['stock'] < 1)>{{ $variant['meta'] }}<small>{{ $money($variant['unit_price']) }}</small></button>@endforeach</div></div>@endif
            <div class="description-area"><h3>সংক্ষিপ্ত বিবরণ</h3><p>{{ strip_tags($product->short_description ?? '') ?: 'পণ্যের বিস্তারিত তথ্য নিচে দেখুন।' }}</p><div class="features-title">পণ্যের তথ্য</div><div class="feature-list"><div class="feature-item"><i class="fa-solid fa-circle-check"></i><span>{{ $product->category?->name }} · {{ $product->brand?->name ?: $product->name }}</span></div><div class="feature-item"><i class="fa-solid fa-circle-check"></i><span>নির্বাচিত পণ্যের দাম ও স্টক অনুযায়ী অর্ডার</span></div>@if($product->installment_enabled)<div class="feature-item"><i class="fa-solid fa-circle-check"></i><span>উপলব্ধ প্ল্যান অনুযায়ী ডাউন পেমেন্ট ও কিস্তি</span></div>@endif</div></div>
            <a class="product-checkout-link" href="{{ route('checkout') }}"><i class="fa-solid fa-cart-shopping"></i> আপনার কার্ট দেখুন</a>
        </div>
        <aside class="purchase-panel"><div class="purchase-main"><div class="price-area"><div class="price-label">নগদ মূল্য</div><div class="main-price" id="mainPrice">{{ $money($selected['unit_price']) }}</div><del id="oldPrice" @if($selected['old_price'] <= $selected['unit_price']) hidden @endif>{{ $money($selected['old_price']) }}</del></div><div class="purchase-divider"></div>
            <div class="purchase-mode"><button type="button" class="mode-btn active" data-mode="cash">নগদে কিনুন</button><button type="button" class="mode-btn" data-mode="installment" @disabled(empty($selected['plans']))>কিস্তিতে নিন</button></div>
            <div class="cash-content" id="cashContent"><div class="cash-info"><strong id="cashTotal">এককালীন {{ $money($selected['unit_price']) }}</strong><span>সম্পূর্ণ মূল্য Main Balance থেকে পরিশোধ করুন</span></div></div>
            <div class="installment-content" id="installmentContent" hidden><div class="emi-heading"><strong>কিস্তির প্ল্যান</strong><span>আপনার সুবিধামতো বেছে নিন</span></div><div class="emi-options" id="emiOptions"></div><div class="emi-summary" id="emiSummary"></div></div>
            <div class="quantity-row"><span>পরিমাণ</span><div class="quantity-control"><button type="button" id="qtyMinus" aria-label="পরিমাণ কমান">−</button><strong id="qtyValue">1</strong><button type="button" id="qtyPlus" aria-label="পরিমাণ বাড়ান">+</button></div></div>
            <form id="productPurchaseForm" action="{{ route('product.cart', $product->slug) }}" method="post">@csrf<div class="action-stack"><button type="submit" class="purchase-btn buy-btn" id="buyNow" @disabled($selected['stock'] < 1)><i class="fa-solid fa-lock me-1"></i> এখনই কিনুন</button><button type="button" class="purchase-btn cart-btn" id="addToCart" @disabled($selected['stock'] < 1)><i class="fa-solid fa-cart-shopping me-1"></i> কার্টে যোগ করুন</button><button type="button" class="purchase-btn wishlist-btn" id="saveProduct" aria-pressed="{{ $saved ? 'true' : 'false' }}"><i class="{{ $saved ? 'fa-solid' : 'fa-regular' }} fa-heart me-1"></i> পছন্দের তালিকায় রাখুন</button></div></form>
            <div class="purchase-help"><i class="fa-solid fa-circle-info"></i><div><strong>Main Balance থেকে নিরাপদে পেমেন্ট</strong><span>চেকআউটে দাম, ঠিকানা ও ডেলিভারি যাচাই করে অর্ডার নিশ্চিত করুন।</span></div></div>
        </div></aside>
    </section>
    <section class="details-section"><div class="detail-tabs" role="tablist" aria-label="পণ্যের বিস্তারিত">@foreach(['description' => 'বিবরণ', 'specification' => 'স্পেসিফিকেশন', 'reviews' => 'রিভিউ ('.$reviewCount.')', 'warranty' => 'ওয়ারেন্টি ও রিটার্ন', 'delivery' => 'ডেলিভারি'] as $id => $label)<button type="button" class="detail-tab {{ $loop->first ? 'active' : '' }}" role="tab" id="tab-{{ $id }}" aria-controls="{{ $id }}" aria-selected="{{ $loop->first ? 'true' : 'false' }}" data-tab="{{ $id }}">{{ $label }}</button>@endforeach</div>
        <div class="tab-content-panel active" id="description" role="tabpanel" aria-labelledby="tab-description"><div class="description-grid"><div><h3>{{ $product->name }}</h3><p class="product-full-description">{{ strip_tags($product->description ?? $product->short_description ?? '') ?: 'বিস্তারিত বিবরণ এখনও যোগ করা হয়নি।' }}</p></div><div><h3>কেনাকাটার পদ্ধতি</h3><p>নগদে কিনলে সম্পূর্ণ মূল্য এবং কিস্তিতে নিলে নির্বাচিত প্ল্যানের ডাউন পেমেন্ট আজ দিতে হবে। পরবর্তী কিস্তির পরিমাণ ও সময়সূচি অর্ডারে সংরক্ষিত থাকবে।</p></div></div></div>
        <div class="tab-content-panel" id="specification" role="tabpanel" aria-labelledby="tab-specification"><table class="spec-table"><tbody><tr><td>পণ্য</td><td>{{ $product->name }}</td></tr><tr><td>ব্র্যান্ড</td><td>{{ $product->brand?->name ?? 'প্রযোজ্য নয়' }}</td></tr><tr><td>ক্যাটাগরি</td><td>{{ $product->category?->name }}</td></tr><tr><td>SKU</td><td>{{ $product->sku }}</td></tr>@foreach($product->variants->where('status', true)->flatMap->attributeValues->unique('id')->groupBy('attribute.name') as $attribute => $values)<tr><td>{{ $attribute }}</td><td>{{ $values->pluck('value')->implode(', ') }}</td></tr>@endforeach</tbody></table></div>
        <div class="tab-content-panel" id="reviews" role="tabpanel" aria-labelledby="tab-reviews">
            @include('theme.partials.product-reviews')
        </div>
        <div class="tab-content-panel" id="warranty" role="tabpanel" aria-labelledby="tab-warranty"><div class="description-grid"><div><h3>ওয়ারেন্টি</h3><p>এই পণ্যের জন্য আলাদা ওয়ারেন্টির তথ্য এখনও যোগ করা হয়নি। কেনার আগে বিক্রেতার সঙ্গে শর্ত নিশ্চিত করুন।</p></div><div><h3>রিটার্ন</h3><p>রিটার্নের বিস্তারিত শর্ত জানতে বিক্রেতার সঙ্গে যোগাযোগ করুন।</p></div></div></div>
        <div class="tab-content-panel" id="delivery" role="tabpanel" aria-labelledby="tab-delivery"><div class="description-grid">@foreach($shippingMethods as $method)<div><h3>{{ $method->name }}</h3><p>চার্জ {{ $money(\App\Services\PurchaseService::cents($method->charge)) }} থেকে। চূড়ান্ত চার্জ ঠিকানার অঞ্চল অনুযায়ী চেকআউটে দেখানো হবে।</p></div>@endforeach</div></div>
    </section>
    @if($related->isNotEmpty())<section class="related-section"><div class="section-head"><h2>আপনার জন্য আরও পণ্য</h2><a href="{{ route('products', ['category' => $product->category?->slug]) }}">সব দেখুন <i class="fa-solid fa-chevron-right"></i></a></div><div class="related-grid">@foreach($related as $item)<a href="{{ $item['url'] }}" class="related-card"><div class="related-image">@if($item['image'])<img src="{{ $item['image'] }}" alt="{{ $item['name'] }}" loading="lazy">@else<div class="purchase-image-placeholder"><i class="fa-solid fa-box-open"></i></div>@endif</div><div class="related-name">{{ $item['name'] }}</div><div class="related-sub">{{ $item['meta'] }}</div><div class="related-price"><strong>{{ $money($item['unit_price']) }}</strong>@if($item['old_price'] > $item['unit_price'])<del>{{ $money($item['old_price']) }}</del>@endif</div><div class="related-bottom"><span>বিস্তারিত দেখুন</span><span class="mini-cart-btn"><i class="fa-solid fa-arrow-right"></i></span></div></a>@endforeach</div></section>@endif
    <div class="mobile-buy-bar"><div class="mobile-price"><span id="mobilePriceLabel">নগদ মূল্য</span><strong id="mobilePriceValue">{{ $money($selected['unit_price']) }}</strong></div><button type="button" class="mobile-buy-btn" id="mobileBuy">এখনই কিনুন</button></div>
    <dialog id="productGallery" class="product-gallery-dialog" aria-labelledby="galleryTitle"><button type="button" class="gallery-close" aria-label="বন্ধ করুন">×</button><p id="galleryTitle">পণ্যের ছবি</p><img alt="{{ $product->name }}" draggable="false"><div><button type="button" id="galleryPrev" aria-label="আগের ছবি">‹</button><span id="galleryCount" role="status" aria-live="polite"></span><button type="button" id="galleryNext" aria-label="পরের ছবি">›</button></div></dialog>
</div>
@endsection
@push('style')<link rel="stylesheet" href="{{ asset('assets/theme/css/product-detail.css') }}">@endpush
@push('script')
<script>window.productPurchase = {{ Illuminate\Support\Js::from(['selected' => $selected, 'variants' => $variants, 'hasVariant' => $product->has_variant, 'images' => $images, 'wishlistUrl' => route('product.wishlist', $product->slug), 'loginUrl' => route('checkout'), 'authenticated' => auth()->check()]) }};</script>
<script src="{{ asset('assets/theme/js/product-detail.js') }}" defer></script>
@endpush
